language: ruby
rvm:
  - 2.3
  - 2.4
  - jruby
gemfile:
  - Gemfile
  - Gemfile.rails-5.0.x
  - Gemfile.rails-5.1.x
script: ./bin/rspec spec
before_install:
  - gem install bundler
notifications:
  disable: true
