sudo: false
dist: xenial
cache: bundler
language: ruby
rvm:
  - 2.6
  - 2.7
  - 3.0
gemfile:
  - Gemfile
  - Gemfile.rails-5.0.x
  - Gemfile.rails-5.1.x
  - Gemfile.rails-6.0.x
jobs:
  exclude:
    - rvm: 3.0
    - gemfile: Gemfile.rails-5.0.x
  exclude:
    - rvm: 3.0
    - gemfile: Gemfile.rails-5.1.x
script: "./bin/rspec spec"
before_install:
  - gem install bundler
notifications:
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: Qng7FzbYWSU+R5Ou+hsg3EiyGwWQ2DVEP/Oc3zksVBT0zGy+/c2XgIvbZvw9KdcR0TNW4sLa135twwyQS5Qnfjq/jogKrBnR9uHvxvvVIIvN/kPO8HG0XFXg4IW+M/pbC25iZMo/x1HnYlKqWpCol8d86fbtjL8tT/clB10ulRM=
  gem: carpentry
  on:
    tags: true
    repo: kiskolabs/carpentry
    ruby: 2.4
    condition: "$BUNDLE_GEMFILE = $PWD/Gemfile"
