language: ruby
rvm:
  - 2.2.1
  - 2.1.5
  - jruby-19mode
gemfile:
  - Gemfile
  - Gemfile.rails-4.1.x
  - Gemfile.rails-4.2.x
bundler_args: ""
script: "bundle exec rake spec"
notifications:
  disable: true
