language: ruby
rvm:
  - 2.3
  - 2.4
  - jruby
gemfile:
  - Gemfile
  - Gemfile.rails-4.2.x
  - Gemfile.rails-5.0.x
  - Gemfile.rails-5.1.x
bundler_args: ""
script: "bundle exec rake spec"
before_install:
  - gem install bundler
notifications:
  disable: true
